import { Lato, Montserrat } from 'next/font/google';
import Header from '@/components/Header';
import Footer from "@/components/Footer";
import './globals.css';

export const lato = Lato({
  subsets: ['latin'],
  weight: ['300']
});

export const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['600']
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang='pt-BR'>
      <body className='box-border flex flex-col'>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
};
